"""Add uploads and sales records

Revision ID: 98410b9f9fc2
Revises: 3d0899cafa3b
Create Date: 2026-08-23 16:20:48.721113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98410b9f9fc2'
down_revision = '3d0899cafa3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uploads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stored_filename')
    )
    with op.batch_alter_table('uploads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_uploads_business_id'), ['business_id'], unique=False)

    op.create_table('sales_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('upload_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('family', sa.String(length=150), nullable=False),
    sa.Column('sales', sa.Float(), nullable=False),
    sa.Column('onpromotion', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sales_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sales_records_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_records_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_records_family'), ['family'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_records_upload_id'), ['upload_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_records_upload_id'))
        batch_op.drop_index(batch_op.f('ix_sales_records_family'))
        batch_op.drop_index(batch_op.f('ix_sales_records_date'))
        batch_op.drop_index(batch_op.f('ix_sales_records_business_id'))

    op.drop_table('sales_records')
    with op.batch_alter_table('uploads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_uploads_business_id'))

    op.drop_table('uploads')
    # ### end Alembic commands ###
