"""Add forecast runs and forecasts

Revision ID: a696e151d500
Revises: 98410b9f9fc2
Create Date: 2026-08-24 22:23:26.558991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a696e151d500'
down_revision = '98410b9f9fc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forecast_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('upload_id', sa.Integer(), nullable=False),
    sa.Column('horizon_days', sa.Integer(), nullable=False),
    sa.Column('forecast_start_date', sa.Date(), nullable=False),
    sa.Column('forecast_end_date', sa.Date(), nullable=False),
    sa.Column('family_count', sa.Integer(), nullable=False),
    sa.Column('future_onpromotion', sa.Float(), nullable=False),
    sa.Column('excluded_families', sa.JSON(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('forecast_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_forecast_runs_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_forecast_runs_upload_id'), ['upload_id'], unique=False)

    op.create_table('forecasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('forecast_run_id', sa.Integer(), nullable=False),
    sa.Column('family', sa.String(length=150), nullable=False),
    sa.Column('forecast_date', sa.Date(), nullable=False),
    sa.Column('predicted_sales', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['forecast_run_id'], ['forecast_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('forecast_run_id', 'family', 'forecast_date', name='uq_forecast_run_family_date')
    )
    with op.batch_alter_table('forecasts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_forecasts_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_forecasts_family'), ['family'], unique=False)
        batch_op.create_index(batch_op.f('ix_forecasts_forecast_date'), ['forecast_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_forecasts_forecast_run_id'), ['forecast_run_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forecasts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_forecasts_forecast_run_id'))
        batch_op.drop_index(batch_op.f('ix_forecasts_forecast_date'))
        batch_op.drop_index(batch_op.f('ix_forecasts_family'))
        batch_op.drop_index(batch_op.f('ix_forecasts_business_id'))

    op.drop_table('forecasts')
    with op.batch_alter_table('forecast_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_forecast_runs_upload_id'))
        batch_op.drop_index(batch_op.f('ix_forecast_runs_business_id'))

    op.drop_table('forecast_runs')
    # ### end Alembic commands ###
